#!/bin/sh

### BEGIN INIT INFO
# Provides: ginger
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Start Ginger at boot time
### END INIT INFO

BASE_DIR=`dirname $0`
BASE_DIR=`readlink -m $BASE_DIR`
BASE_DIR=`dirname $BASE_DIR`
BASE_DIR=`dirname $BASE_DIR`
PID_FILE=$BASE_DIR/unicorn.pid
CURRENT=$BASE_DIR/current

source ~/.rbenv/bin/rbenv

function stop_service {
	if [ -f $PID_FILE ]; then kill `cat $PID_FILE`; fi

	while [ -f $PID_FILE ]; do
		sleep 1
	done
}

function start_service {
	cd $CURRENT

	if [ -f $PID_FILE ]
	then
		kill `cat $PID_FILE`
		rm $PID_FILE
	fi

	rbenv exec unicorn -c $CURRENT/unicorn.rb -p 4567 -E development -D
}

case $1 in
start)
	start_service
	;;

stop)
	stop_service
	;;

restart)
	stop_service
	start_service
	;;

status)
	if [ -f $PID_FILE ]
	then
		echo PID: `cat $PID_FILE`
	fi
	;;

*)
	echo Unexpected command
	exit 1
esac

